### ISSUE TITLE
clone of dedicated ATP database..

### ISSUE THREAD

**Issue by AmanDhaka1986** [mlinxfeld/terraform-oci-atp#1]
Hi All,
Trying to create clone of dedicated autonomous database via terraform but failing with below error, any help plz..

Error: Service error:InvalidParameter. Unable to process JSON input. http status code: 400. Opc request id: bb415ef662288245c9d2b8053d2b4381/034594DCD65AB3EA7215040DFDC05125/AAC446F2E69FDA942406E1B2F47F1A5D

on main.tf line 1, in resource "oci_database_autonomous_database" "autonomous_database":
1: resource "oci_database_autonomous_database" "autonomous_database" {

Terraform file ...

[oracle@daznadmin dedicated_exadata]$ cat main.tf
resource "oci_database_autonomous_database" "autonomous_database" {
admin_password = ""
compartment_id = "ocid1.compartment.oc1..a***********"
cpu_core_count = "8"
data_storage_size_in_tbs = "2"
db_name = "SP****"
clone_type = "FULL"
display_name = "SP*****"
is_auto_scaling_enabled = "false"
is_dedicated = "true"
license_model = "PAID"
source = "DATABASE"
autonomous_container_database_id = "ocid1.autonomouscontainerdatabase.oc1*******"
source_id = "ocid1.autonomousdatabase.oc1.uk-london-********"
}

**Comment by lfeldman** [comment]
This repo is for ATP-S
